sigmas/home/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import *
from django.contrib.auth import views as auth_views
from .views import *


app_name = 'home'

urlpatterns = [
	url(r'^$', do_login ,name='do_login'),
	url(r'^logout/$', do_logout ,name='do_logout'),
	url(r'^home/$', home ,name='home'),
	url(r'^home/produtos/$',captura_products, name='produtos'),
	url(r'^home/comanda/$',comanda, name='comandas'),
]

sigmas/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    url(r'^', include('sigmas.home.urls', namespace='home')),
    url('admin/', admin.site.urls),
]

sigmas/home/models.py
import re
from datetime import date, datetime
from django.db import models
from django.core import validators
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone

class estoque(models.Model):
	marca = models.CharField(
		'Marca do produto',
		help_text = 'Informe a marca do produto',
		max_length = 300,)
	nome = models.CharField(
		'Nome do produto',
		help_text= 'Informe o nome do produto',
		max_length = 150,)
	sabor = models.CharField(
		'Sabor do produto',
		help_text= 'Informe o sabor do produto',
		max_length=150,)
	categoria = models.CharField(
		'Categoria do produto',
		help_text= 'Informe a categoria do produto',
		max_length=150,
		default="", 
		editable=True)
	preco = models.CharField(
		'Preço do produto',
		help_text= 'Digite o preço do produto',
		max_length= 50,)
	quantidade = models.CharField(
		'Quantidade desejada',
		help_text= 'Informe a quantidade desejada de produtos',
		max_length=100,)

class comanda(models.Model):
	nome_cliente = models.CharField(
		'Nome do cliente',
		help_text = 'Informe o nome do cliente',
		max_length = 300,)
	sexo = (
		('Masculino', 'Masculino'),
		('Feminino', 'Feminino'),
		'Genero do cliente',)
	situacao =(
		('V','Vip'),
		('P','Pagante'))
	cpf = models.CharField(
		'Marca do produto',
		unique=True,
		help_text = 'Informe a marca do produto',
		max_length = 14,)
	comanda = models.CharField(
		'Comanda',
		help_text = 'Informe o número da comanda',
		max_length = 8,)
	mesas = models.CharField(
		'Mesa',
		help_text = 'Informe a mesa do cliente',
		max_length = 3,)
	narguiles = models.CharField(
		'Narguile',
		help_text = 'Informe a marca do produto',
		max_length = 5,)
	rua = models.CharField(
		'Endereço do cliente',
		help_text = 'Endereço do cliente',
		max_length = 300,)
	cidade = models.CharField(
		'Cidade do Cliente',
		help_text = 'Informe a cidade do cliente',
		max_length = 300,)
	estado = models.CharField(
		'Marca do produto',
		help_text = 'Informe a marca do produto',
		max_length = 300,)
	celular = models.CharField(
		'Marca do produto',
		help_text = 'Informe a marca do produto',
		max_length = 300,)
	email = models.CharField(
		'Marca do produto',
		help_text = 'Informe a marca do produto',
		max_length = 300,)

sigmas/home/forms.py
from django import forms
from django.forms import ModelForm
from .models import estoque,comanda

class EstoqueForm(forms.ModelForm):
	
	class Meta:	
		model = estoque
		fields ='__all__'
		widgets = {

		'marca':forms.TextInput(attrs={'class':'form-control','maxlength':255,'placeholder':'Marca'}),
		'nome':forms.TextInput(attrs={'class':'form-control','maxlength':255,'placeholder':'Nome'}),
		'sabor':forms.TextInput(attrs={'class':'form-control','maxlength':255,'placeholder':'Sabor'}),
		'categoria':forms.TextInput(attrs={'class':'form-control','maxlength':255,'placeholder':'Categoria'}),
		'preco':forms.TextInput(attrs={'class':'form-control','maxlength':255,'placeholder':'Preco'}),
		'quantidade':forms.TextInput(attrs={'class':'form-control','maxlength':255,'placeholder':'Quantidade'}),

		}
class ComandaForm(forms.ModelForm):

	class Meta:
		model = comanda
		fields = '__all__'
		widgets = {
		'nome_cliente':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite o nome do cliente'}),
		'sexo':forms.TextInput(attrs={'class':'form-control','maxlength':300,}),
		'situacao':forms.TextInput(attrs={'class':'form-control','maxlength':300,}),
		'cpf':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite o cpf do cliente'}),
		'comanda':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite a comanda do cliente'}),
		'mesas':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Qual a mesa do cliente'}),
		'narguiles':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Quantidade de narguiles'}),
		'rua':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite a rua do cliente'}),
		'cidade':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite a cidade do cliente'}),
		'estado':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite o estado do cliente'}),
		'celular':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite o celular do cliente'}),
		'email':forms.TextInput(attrs={'class':'form-control','maxlength':300,'placeholder':'Digite o email do cliente'}),
		}

sigmas/home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import (TemplateView, View, ListView, DetailView)
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from  django.views import defaults
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import *
from .forms import EstoqueForm, ComandaForm

@login_required
def home(request):
	template_name = 'index.html'

	return render(request,template_name)

def do_login(request):
	if request.method == 'POST':
		user = authenticate(username=request.POST['username'], password=request.POST["password"])
		if user is not None:
			login(request,user)
			return redirect('/home')
		else:
			messages.error(request, 'Usuário ou senha incorreta')
	return render(request,'login.html')

def do_logout(request):
	logout(request)
	return redirect('/')

def comanda(request):
	form = ComandaForm(request.POST or None)
	if form.is_valid():
		form.save()
	return render(request,'pages/comanda.html',{'form':form,})

def captura_products(request):
	capture = estoque.objects.all()
	form = EstoqueForm(request.POST or None)
	if form.is_valid():
		form.save()	
	
	return render(request,'pages/product.html',{'capture':capture,'form':form,})

sigmas/home/templates/base/aside.html
{%load static%}
<aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- User profile -->
                <div class="user-profile" style="background: url({% static '/assets/images/background/profile.jpg' %}) no-repeat;">
                    <!-- User profile image -->
                    <div class="profile-img"> <img src="{% static '/assets/images/users/profile.png' %}" alt="user" /> </div>
                    <!-- User profile text-->
                    <div class="profile-text"> <a href="#" class="dropdown-toggle u-dropdown" data-toggle="dropdown"
                            role="button" aria-haspopup="true" aria-expanded="true">Administrador</a>
                        <div class="dropdown-menu animated flipInY"> <a href="#" class="dropdown-item"><i class="ti-user"></i>
                                Meus Relatórios</a> <a href="#" class="dropdown-item"><i class="ti-wallet"></i> Meu Perfil</a>
                            <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"><i class="ti-settings"></i>
                                Configurações</a>
                            <div class="dropdown-divider"></div> <a href="{% url 'home:do_logout'%}" class="dropdown-item"><i class="fa fa-power-off"></i>
                                Logout</a>
                        </div>
                    </div>
                </div>
                <!-- End User profile text-->
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="nav-small-cap">Menu</li>
                        <li> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class=" icon-basket-loaded"></i><span
                                    class="hide-menu">Caixa</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="{% url 'home:comandas' %}">Comanda</a></li>
                                <li><a href="#">Histórico</a></li>
                                <li><a href="#">Pedidos</a></li>
                            </ul>
                        </li>
                        <li> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-laptop-windows"></i><span
                                    class="hide-menu">Relatórios</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="#">Vendas</a></li>
                                <li><a href="#">Clientes</a></li>
                                <li><a href="#">Produtos</a></li>
                                <li><a href="#">Gastos</a></li>
                            </ul>
                        </li>
                        <li> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-bullseye"></i><span
                                    class="hide-menu">Estoque</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="{% url 'home:produtos' %}">Produtos</a></li>
                                <li><a href="#">Saída</a></li>
                                <li><a href="#">Produção</a></li>
                            </ul>
                        </li>
                        <li class="nav-devider"></li>
               </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
            <!-- Bottom points-->
            <div class="sidebar-footer">
                <!-- item--><a href="#" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
                <!-- item--><a href="#" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
                <!-- item--><a href="{% url 'home:do_logout'%}" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
            </div>
            <!-- End Bottom points-->
        </aside>

sigmas/home/templates/base/footer.html
{% load static %}
<footer class="footer">
    © 2019 Desenvolvido por Eduardo Henrique | Sigma's Hookah - Lounge e Tabacaria
</footer>

sigmas/home/templates/base/header.html
{%load static%}
<!-- Barra de cima de menu - arquivo de configuração pages.scss -->
<header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- Logo -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'home:home' %}">
                            <!-- Light Logo icon -->
                            <span>SIGMA'S</span>
                    </a>
                </div>
                <!-- End Logo -->
               <div class="navbar-collapse">
                    <!-- toggle and nav items -->
                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark"
                                href="{% static 'javascript:void(0)' %}"><i class="mdi mdi-menu"></i></a> </li>
                        <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark"
                                href="{% static 'javascript:void(0)' %}"><i class="ti-menu"></i></a> </li>
                        <!-- Search -->
                        <li class="nav-item hidden-sm-down search-box"> <a class="nav-link hidden-sm-down text-muted waves-effect waves-dark"
                                href="{% static 'javascript:void(0)' %}"><i class="ti-search"></i></a>
                            <form class="app-search">
                                <input type="text" class="form-control" placeholder="Search & enter"> <a class="srh-btn"><i
                                        class="ti-close"></i></a> </form>
                        </li>                
                    </ul>
                    <!-- User profile and search -->
                    <ul class="navbar-nav my-lg-0">
                        <!-- Profile -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="#" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false"><img src="{% static '/assets/images/users/1.jpg' %}" alt="user"
                                    class="profile-pic" /></a>
                            <div class="dropdown-menu dropdown-menu-right scale-up">
                                <ul class="dropdown-user">
                                    <li>
                                        <div class="dw-user-box">
                                            <div class="u-img"><img src="{% static '/assets/images/users/1.jpg' %}" alt="user"></div>
                                            <div class="u-text">
                                                <h4>Administrador</h4>
                                                <p class="text-muted">admin@sigmas.com</p><a href="#" class="btn btn-rounded btn-danger btn-sm">Ver
                                                    Perfil</a>
                                            </div>
                                        </div>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#"><i class="ti-user"></i> Meu Perfil</a></li>
                                    <li><a href="#"><i class="ti-wallet"></i> Meus Relatórios</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#"><i class="ti-settings"></i>Configurações</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{% url 'home:do_logout' %}"><i class="fa fa-power-off"></i> Logout</a></li>
                                </ul>
                            </div>
                        </li>                    
            </nav>       
</header> 

sigmas/home/templates/base/loader.html
{%load static%}
<!-- Carregamento da página - arquivo de configuração spinners.css --->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
<!---============================================================== -->

sigmas/home/templates/base/nova_comanda.html
{%load static%}
<div id="add-contact" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
 <div class="modal-dialog modal-xl">
  <div class="modal-content">
   <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">× </button>
     <h4 class="modal-title" id="myModalLabel">Fechar</h4> </div>
        <div class="modal-body">
            <div class="col-lg-12">
    <div class="card card-outline-info">
        <div class="card-header">
            <h4 class="m-b-0 text-white">Abrir nova comanda</h4>
        </div>
        <div class="card-body">
<form class="form-horizontal" method= "post" action= "{% url 'home:comandas' %}">
  {% csrf_token %}

<div class="form-body">
    <h3 class="box-title">Informações do cliente</h3>
    <hr class="m-t-0 m-b-40">
    <div class="row">
        
<div class="col-md-6">
<div class="form-group row">
    <label class="control-label text-right col-md-3">Nome</label>
    <div class="col-md-9">
   {{form.nome_cliente}}
  </div>
  </div>
</div>

<div class="col-md-6">
<div class="form-group row">
    <label class="control-label text-right col-md-3">CPF</label>
    <div class="col-md-9">
   {{form.cpf}}
  </div>
  </div>
</div>
</div>
        
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
        <label class="control-label text-right col-md-3">Sexo</label>
<div class="col-md-9">
    <select class="form-control custom-select">
        <option value="">Masculino</option>
        <option value="">Feminino</option>
    </select>
    </div>
 </div>
</div>

<div class="col-md-6">
<div class="form-group row">
    <label class="control-label text-right col-md-3">Comanda</label>
    <div class="col-md-9">
  {{form.comanda}} 
  </div>
  </div>
</div> 
</div>
        
<div class="row">
<div class="col-md-6">
<div class="form-group row">
   <label class="control-label text-right col-md-3">Situação</label>
<div class="col-md-9">
<div class="m-b-10">
<label class="custom-control custom-radio">
 <input id="radio3" name="radio" type="radio" class="custom-control-input">
 <span class="custom-control-label">Cobrar</span>
</label>
<label class="custom-control custom-radio">
    <input id="radio4" name="radio" type="radio" class="custom-control-input">
<span class="custom-control-label">Vip</span>
</label>
 </div>
</div>
</div>
</div>


<div class="col-md-6">
<div class="form-group row">
    <label class="control-label text-right col-md-3">Mesas</label>
    <div class="col-md-9">
  {{form.mesas}} 
  </div>
  </div>
</div> 
</div>

<div class="row">
<div class="col-md-6">
<div class="form-group row">
    <label class="control-label text-right col-md-3">Narguiles</label>
    <div class="col-md-9">
  {{form.narguiles}} 
  </div>
  </div>
</div> 
</div>
</div>
                                        
<h3 class="box-title">Endereços</h3>
<hr class="m-t-0 m-b-40">
                                   
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label class="control-label text-right col-md-3">Rua</label>
            <div class="col-md-9">
            {{form.rua}}             
            </div>
        </div>
    </div>
   </div>

<div class="row">
<div class="col-md-6">
    <div class="form-group row">
        <label class="control-label text-right col-md-3">Cidade</label>
    <div class="col-md-9">
        {{form.cidade}}
    </div>
</div>
</div>

    <div class="col-md-6">
        <div class="form-group row">
       <label class="control-label text-right col-md-3">Estado</label>
        <div class="col-md-9">
            {{form.estado}}
        </div>
    </div>
</div>
</div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group row">
        <label class="control-label text-right col-md-3">Celular</label>
                <div class="col-md-9">
                    {{form.celular}}
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group row">
        <label class="control-label text-right col-md-3">Email</label>
                <div class="col-md-9">
                    {{form.email}}
                </div>
            </div>
        </div>        
       </div>
      </div>
    <hr>
                                    
<div class="form-actions">
 <div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-success">Salvar</button>
                <button type="button" class="btn btn-inverse" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
     </div>
 <div class="col-md-6">
</div>
</div>
</div>
  </form>
  </div>
    </div>
     </div>
      </div>
        </div>
            </div>
              </div>

sigmas/home/templates/pages/product.html
{%load static%}
<!DOCTYPE html>
<html lang="pt-br">
{% include 'base/head.html' %}

<body class="fix-header fix-sidebar card-no-border">

    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    
    <div id="main-wrapper">
{% include 'base/header.html' %}
{% include 'base/aside.html' %}
        <div class="page-wrapper">
            <div class="container-fluid">
                <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Produtos</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'home:home' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item active">Produtos</li>
                        </ol>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12"> 
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Produtos</h4>
                                <h6 class="card-subtitle">Aqui você pode adicionar e editar produtos!</h6>
                                <div class="table-responsive m-t-40">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Marca</th>
                                                <th>Nome</th>
                                                <th>Sabor</th>
                                                <th>Categoria</th>
                                                <th>Preço</th>
                                                <th>Quantidade</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                            {% for capt in capture %}
                                <tr>
                                    <td>{{capt.marca}}</td>
                                    <td>{{capt.nome}}</td>
                                    <td>{{capt.sabor}}</td>
                                    <td>{{capt.categoria}}</td>
                                    <td>{{capt.preco}}</td>
                                    <td>{{capt.quantidade}}</td>
                                </tr>
                                {%endfor%}
                                        </tbody>
                                    </table>
                                </div>
                            <button type="button" class="btn waves-effect waves-light btn-secondary"" data-toggle="modal" data-target="#add-contact">Adicionar</button>
                            <button type="button" class="btn waves-effect waves-light btn-warning">Editar</button>
                            

    <div id="add-contact" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title" id="myModalLabel">Adiciona novo produto</h4> </div>
        <div class="modal-body">    
    <form class="form-horizontal form-material" method= "post" action= "{% url 'home:produtos' %}">
            {% csrf_token %}
    <div class="form-group">
    
    <div class="col-md-12 m-b-20">
    {{form.marca}}
    </div>         
    
    <div class="col-md-12 m-b-20">
    {{form.nome}}
    </div>                                              
    
    <div class="col-md-12 m-b-20">
    {{form.sabor}}
    </div>
                                                  
    <div class="col-md-12 m-b-20">
    {{form.categoria}}
    </div>
                                                  
    <div class="col-md-12 m-b-20">
    {{form.preco}}
    </div>
                                                        
    <div class="col-md-12 m-b-20">
    {{form.quantidade}}
    </div>                                                       
    <button type="submit" class="btn btn-info waves-effect">Salvar</button>
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>    
    </div>
    </form>
    </div>
        </div>
            </div>
              </div>
                </div>
             </div>
            </div>
                </div>


            <div class="right-sidebar">
                    <div class="slimscrollright">
                        <div class="rpanel-title"> Service Panel
                            <span>
                                <i class="ti-close right-side-toggle"></i>
                            </span>
                        </div>
                        <div class="r-panel-body">
                            <ul id="themecolors" class="m-t-20">
                                <li>
                                    <b>With Light sidebar</b>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" data-theme="default" class="default-theme">1</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" data-theme="green" class="green-theme">2</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" data-theme="red" class="red-theme">3</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" data-theme="blue" class="blue-theme working">4</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" data-theme="purple" class="purple-theme">5</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" data-theme="megna" class="megna-theme">6</a>
                                </li>                
                            </ul>
                        </div>
                    </div>
            </div>

            </div>
{% include 'base/footer.html'%}
        </div>
    </div>
    <script src="{% static '/assets/plugins/jquery/jquery.min.js' %}"></script>

    <script src="{% static '/assets/plugins/popper/popper.min.js' %}"></script>
    <script src="{% static '/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>

    <script src="{% static 'js/waves.js' %}"></script>

    <script src="{% static 'js/sidebarmenu.js' %}"></script>

    <script src="{% static '/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <script src="{% static '/assets/plugins/sparkline/jquery.sparkline.min.js' %}"></script>

    <script src="{% static 'js/custom.min.js' %}"></script>

    <script src="{% static '/assets/plugins/datatables/datatables.min.js' %}"></script>

    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <script>
        $(function () {
            $('#myTable').DataTable();
            $(function () {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function (settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function (group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function () {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
    <script src="{% static '/assets/plugins/styleswitcher/jQuery.style.switcher.js' %}"></script>
</body>


<!-- Mirrored from wrappixel.com/demos/admin-templates/material-pro/material/table-data-table.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Feb 2019 11:38:37 GMT -->
</html>